#!/usr/bin/env bash

PROJECTPATH="."
MESSAGE="Install Laravel"
QUIET=false
DEVELOP=false
AUTH=false
NODE=true
CODEEDITOR="/usr/local/bin/code"
BROWSER=""
LINK=false
SECURE=false
FRONTEND="vue"
CREATE_DATABASE=true
DB_USERNAME="root"
DB_PASSWORD=""
