alias b='brew'
alias bv='brew --version'
alias bsu='brew update'
alias bh='brew help'
alias ba='brew install'
alias bl='brew list'
alias bu='brew upgrade'
alias brm='brew uninstall'
alias bf='brew search'
alias bod='brew outdated'

alias bri='brew reinstall'
alias bca='brew install --cask'
alias bcrm='brew uninstall --cask'

alias bs='brew services'
alias bst='brew services start'
alias bsp='brew services stop'
alias bsr='brew services restart'
alias bsl='brew services list'
