alias b='brew'
alias bv='brew --version'
alias bsu='brew update'
alias bh='brew help'
alias ba='brew install'
alias bl='brew list'
alias bu='brew upgrade'
alias brm='brew uninstall'
alias bf='brew search'
alias bod='brew outdated'

alias bri='brew reinstall'
alias bca='brew install --cask'
alias bcrm='brew uninstall --cask'
