# Gulp
alias glp='gulp'
alias glpw='gulp watch'
alias glpprod='gulp --production'
alias gp='gulp'
alias gpw='gulp watch'
alias gpp='gulp --production'

# NPM
alias np='npm'
alias npi='npm install'
alias npis='npm install --save'
alias npisd='npm install --save-dev'
alias npig='npm install -g'
alias npu='npm update'
alias npug='npm update -g'
alias nps='npm search'
alias nrp='npm run prod'
alias nrd='npm run dev'
alias nrw='npm run watch'

# Yarn
alias y='yarn'
alias yi='yarn install'
alias yrm='yarn remove'
alias ya='yarn add'
alias yad='yarn add --dev'
alias yr='yarn run'
alias yrp='yarn run prod'
alias yrd='yarn run dev'
alias yrw='yarn run watch'
alias yrh='yarn run hot'
alias yp='yarn run prod'
alias yd='yarn run dev'
alias yw='yarn run watch'
alias yh='yarn run hot'
